version: '3.3'
services:
  activemq:
    image: fogsyio/activemq:5.15.9
    cpu_count: 1
    cpu_percent: 15
    mem_limit: 256m
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    environment:
      ACTIVEMQ_NAME: amq
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      TZ: 'Australia/Melbourne'
    volumes:
      - ./data/activemq:/data/activemq
      - ./logs/activemq:/var/log/activemq
  mysql:
    image: mysql:5.7
    cpu_count: 2
    cpu_percent: 25
    mem_limit: 1g
    memswap_limit: 2g
    mem_reservation: 1g
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'Australia/Melbourne'
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./conf/mysql:/etc/mysql/conf.d
